### ISSUE TITLE
Is there any way support view include AsyncImage?

### ISSUE THREAD

**Issue by mny459** [RickeyBoy/ScreenshotableView#1]

**Comment by RickeyBoy** [comment]
Sorry for the late response.

**Comment by RickeyBoy** [comment]
I've succeed with using third-party image pod like Kingfisher. Since it can store remote images in cache, there is no loading phase anymore when ScreenshotableView render again. 🎉

USAGE:
import Kingfisher and use `KFImage(url)` straightly in your ScreenshotableView.

What will happen?
1. View will be rendered when it appears.
2. At this time, KF automatically download url and save image content in cache.
3. When you trigger a screenshot, ScreenshotableView will cause a new render with the image content in cache, so there will be no problem!
